# Generated by Django 5.0.4 on 2024-04-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='slug',
            new_name='title',
        ),
    ]
